### ISSUE TITLE
no Jazzy

### ISSUE THREAD

**Issue by fwarmuth** [clearpathrobotics/roscon2024-workshop-demystifying-ros2-networking#7]
Hey,
just saw that a humble install is expected...
what if i arrive with a running Jazzy setup, makes sense?
workaround options:
- run humble in docker and use Jazzy for GUI (rviz2...)?
- forward X11 from docker?
- Anyone built humble on 24.04?
- maybe i just install 22.04 on another drive?

Any thoughts?
Cheers

**Comment by tonybaltovski** [comment]
Hi,

We provided a Humbe VM using VirtualBox that contains everything needed.  You should be able to use docker with X11 forwarding.  Would one of those two work for you?

**Comment by fwarmuth** [comment]
yea sure! Thanks
i will go for docker, used to that. Keeping the VM as an backup.
looking forward to meet you!
