### ISSUE TITLE
[SERVER_CLIENT_DISCOVERY Error] Wrong locator passed into the server's list “127.0.0.1:11811” -> Function load_environment_server_info

### ISSUE THREAD

**Issue by mdxtinkernick** [clearpathrobotics/roscon2024-workshop-demystifying-ros2-networking#8]
Hi

Trying to run the discovery server example in the downloaded vm and get this error 

`[SERVER_CLIENT_DISCOVERY Error] Wrong locator passed into the server's list “127.0.0.1:11811” -> Function load_environment_server_info`

when running

`ros2 run turtlesim turtlesim_node`

with/wthout using a namespace. get the same error when running the teleop node

have run 

`export ROS_DISCOVERY_SERVER=“127.0.0.1:11811”` 

in each of the windows first. 
Have tried on a pi running jazzy, getting the same result

**Comment by hilary-luo** [comment]
@mdxtinkernick Sometimes when you copy the commands directly out of the slides the quotation marks are not the correct character. Can you please make sure that when you run the export commands that you retype the quotation marks or copy from the code snippet below:

`export ROS_DISCOVERY_SERVER="127.0.0.1:11811"`
